/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoyalPharma;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Changepassword extends javax.swing.JFrame {

    /**
     * Creates new form Changepassword
     */
    public Changepassword() {
        initComponents();

        uid.setText(String.valueOf(LoginClass.uId).toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        uid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        confirmpass = new javax.swing.JPasswordField();
        set = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        changepassbtn = new javax.swing.JButton();
        newaccountbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/Medical-Shop-Software (1)_1.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uid.setText("jLabel3");
        jPanel1.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 240, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("CHANGE PASSWORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 280, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 109, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("New Password   :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password    :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        newpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 240, 40));

        confirmpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassActionPerformed(evt);
            }
        });
        jPanel1.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 240, 40));

        set.setBackground(new java.awt.Color(255, 255, 255));
        set.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        set.setForeground(new java.awt.Color(102, 102, 255));
        set.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/changepassword.png"))); // NOI18N
        set.setText("Set");
        set.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        set.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });
        jPanel1.add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, 40));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(102, 102, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/back.png"))); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/3.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 600, 460));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/24px-new.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 70, 70));

        changepassbtn.setBackground(new java.awt.Color(255, 255, 255));
        changepassbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        changepassbtn.setForeground(new java.awt.Color(0, 204, 153));
        changepassbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/changepassword.png"))); // NOI18N
        changepassbtn.setText("  CHANGE PASSWORD");
        changepassbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        changepassbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changepassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassbtnActionPerformed(evt);
            }
        });
        getContentPane().add(changepassbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 40));

        newaccountbtn.setBackground(new java.awt.Color(255, 255, 255));
        newaccountbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newaccountbtn.setForeground(new java.awt.Color(0, 204, 153));
        newaccountbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/newuser.png"))); // NOI18N
        newaccountbtn.setText("  CREATE NEW ACCOUNT");
        newaccountbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        newaccountbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newaccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newaccountbtnActionPerformed(evt);
            }
        });
        getContentPane().add(newaccountbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 40));

        logoutbtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(0, 204, 153));
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/logout.png"))); // NOI18N
        logoutbtn.setText("             LOGOUT");
        logoutbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 270, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassActionPerformed

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed

        ConfirmPassword changeuser = new ConfirmPassword();
        boolean isUser = false;

        //------------------Label UID---------------------------------//
        changeuser.setUId(Integer.parseInt(uid.getText()));
        Integer user_id = changeuser.getUId();

        String new_pass = String.valueOf(newpass.getPassword());

        changeuser.setConfirmpass(String.valueOf(confirmpass.getPassword()));
        String confirm_pass = changeuser.getConfirmpass();

        String sql = "SELECT * FROM user_details WHERE user_id=?";
        String sql2 = "UPDATE user_details SET password =? WHERE user_id=?";
        try {
            PreparedStatement stmt = DbConnect.getConnection().prepareStatement(sql);
            System.out.println("sql1-----------------");
            stmt.setInt(1, user_id);
            System.out.println(user_id + ".......id.............");

            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {

                isUser = true;
                System.out.println("isUser-----------------");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (new_pass == "" || confirm_pass == "") {
            JOptionPane.showMessageDialog(null, "Please input data.");
        } else if (!isUser) {
            JOptionPane.showMessageDialog(null, "Invalid username or password.");
        } else if (!changeuser.confirmpass(new_pass)) {
            JOptionPane.showMessageDialog(null, "Please type the new password again.");
        } else {
            try {
                PreparedStatement stmt = DbConnect.getConnection().prepareStatement(sql2);
                System.out.println("sql2-----------------");
                stmt.setString(1, confirm_pass);
                stmt.setInt(2, user_id);
//            stmt.setString(3, pass);
                int rs = stmt.executeUpdate();

            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Your password has been changed.");
            Login userchanged = new Login();
            userchanged.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_setActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Changepassword loginuser = new Changepassword();
        MainWindow mw = new MainWindow(loginuser);
        mw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void changepassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassbtnActionPerformed
        Changepassword CP = new Changepassword();
        CP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changepassbtnActionPerformed

    private void newaccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newaccountbtnActionPerformed
        Createnewuser CNU = new Createnewuser();
        CNU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newaccountbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ViewPreviousBills loginuser = new ViewPreviousBills();
        MainWindow mw = new MainWindow(loginuser);
        mw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Changepassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton changepassbtn;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton newaccountbtn;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JButton set;
    private javax.swing.JLabel uid;
    // End of variables declaration//GEN-END:variables
}
