/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoyalPharma;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Deleteitem extends javax.swing.JFrame {

    /**
     * Creates new form Deleteitem
     */
    public Deleteitem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dltall = new javax.swing.JButton();
        dltbil = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        viewstock = new javax.swing.JButton();
        dlt = new javax.swing.JButton();
        viewbills = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        deleteitembutn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        additembutn = new javax.swing.JButton();
        viewstock1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Drug Item");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("DELETE ITEMS");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 18, 280, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Batch No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, 23));

        bno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(bno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 77, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Delete everything");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 123, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Delete bils");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 84, -1));

        dltall.setBackground(new java.awt.Color(255, 255, 255));
        dltall.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dltall.setForeground(new java.awt.Color(0, 204, 153));
        dltall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/remove.png"))); // NOI18N
        dltall.setText("Delete");
        dltall.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dltall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dltall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltallActionPerformed(evt);
            }
        });
        jPanel1.add(dltall, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 120, 40));

        dltbil.setBackground(new java.awt.Color(255, 255, 255));
        dltbil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dltbil.setForeground(new java.awt.Color(0, 204, 153));
        dltbil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/remove.png"))); // NOI18N
        dltbil.setText("Delete");
        dltbil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dltbil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dltbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbilActionPerformed(evt);
            }
        });
        jPanel1.add(dltbil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 120, 40));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 204, 153));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/back.png"))); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 100, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/3.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 960, 560));

        viewstock.setBackground(new java.awt.Color(255, 255, 255));
        viewstock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewstock.setForeground(new java.awt.Color(102, 102, 255));
        viewstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/viewimage.png"))); // NOI18N
        viewstock.setText("  VIEW STOCK");
        viewstock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstockActionPerformed(evt);
            }
        });
        jPanel1.add(viewstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 40));

        dlt.setBackground(new java.awt.Color(255, 255, 255));
        dlt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dlt.setForeground(new java.awt.Color(255, 0, 0));
        dlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/remove.png"))); // NOI18N
        dlt.setText("Delete Drug Item");
        dlt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dlt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        jPanel1.add(dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 210, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -10, -1, 412));

        viewbills.setBackground(new java.awt.Color(255, 255, 255));
        viewbills.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewbills.setForeground(new java.awt.Color(0, 204, 153));
        viewbills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/viewbills.png"))); // NOI18N
        viewbills.setText("DAILY REPORT");
        viewbills.setAutoscrolls(true);
        viewbills.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewbills.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewbills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbillsActionPerformed(evt);
            }
        });
        getContentPane().add(viewbills, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 153));
        jButton3.setText("UPDATE SUPPLIERS");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 153));
        jButton2.setText("UPDATE CUSTOMERS");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 40));

        deleteitembutn.setBackground(new java.awt.Color(255, 255, 255));
        deleteitembutn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteitembutn.setForeground(new java.awt.Color(0, 204, 153));
        deleteitembutn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/remove.png"))); // NOI18N
        deleteitembutn.setText("    DELETE ITEMS");
        deleteitembutn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteitembutn.setBorderPainted(false);
        deleteitembutn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteitembutn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteitembutnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteitembutn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/24px-new.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, 70));

        additembutn.setBackground(new java.awt.Color(255, 255, 255));
        additembutn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        additembutn.setForeground(new java.awt.Color(0, 204, 153));
        additembutn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/additems.png"))); // NOI18N
        additembutn.setText("    UPDATE ITEMS");
        additembutn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        additembutn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        additembutn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additembutnActionPerformed(evt);
            }
        });
        getContentPane().add(additembutn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 270, 40));

        viewstock1.setBackground(new java.awt.Color(255, 255, 255));
        viewstock1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewstock1.setForeground(new java.awt.Color(0, 204, 153));
        viewstock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/viewimage.png"))); // NOI18N
        viewstock1.setText("  VIEW STOCK");
        viewstock1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewstock1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewstock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstock1ActionPerformed(evt);
            }
        });
        getContentPane().add(viewstock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        Add_Drug_Item addnew = new Add_Drug_Item();
        addnew.setBNo(bno.getText());
        String batch = addnew.getBNo();

        if ("".equals(batch)) {
            JOptionPane.showMessageDialog(null, "Please compleat all fields of the form.");
        } else {
            String sql = "DELETE FROM store WHERE BatchNo=?";
            try {
                PreparedStatement stmt = DbConnect.getConnection().prepareStatement(sql);
                stmt.setString(1, batch);
                stmt.executeUpdate();

            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "You were deleted a drug item successfully.");
            /* Login drugdeleted = new Login();
            drugdeleted.setVisible(true);
            this.dispose();*/
            bno.setText("");
        }
    }//GEN-LAST:event_dltActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Deleteitem loginuser = new Deleteitem();
        MainWindow mw= new   MainWindow(loginuser);
        mw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void dltbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltbilActionPerformed

        String sql = "DROP TABLE previousbills";
        String sql2 = "CREATE TABLE `previousbills` (\n" +
        "  `id` int(11) NOT NULL,\n" +
        "  `BatchNo` varchar(6) NOT NULL,\n" +
        "  `GName` varchar(50) DEFAULT NULL,\n" +
        "  `BName` varchar(50) DEFAULT NULL,\n" +
        "  `Qty` int(4) DEFAULT NULL,\n" +
        "  `Exp` date DEFAULT NULL,\n" +
        "  `MRP` double DEFAULT NULL,\n" +
        "  `Amount` double DEFAULT NULL,\n" +
        "  `TotalAmount` double DEFAULT NULL,\n" +
        "  `Date` date DEFAULT NULL,\n" +
        "  `InvoiceNo` int(5) NOT NULL\n" +
        ") ENGINE=InnoDB DEFAULT CHARSET=latin1;";
        String sql3 = "ALTER TABLE `previousbills`\n" +
        "  ADD PRIMARY KEY (`id`);";
        String sql4 = "ALTER TABLE `previousbills`\n" +
        "  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;";
        try {
            PreparedStatement stmt = DbConnect.getConnection().prepareStatement(sql);
            stmt.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            PreparedStatement stmt2 = DbConnect.getConnection().prepareStatement(sql2);
            stmt2.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            PreparedStatement stmt3 = DbConnect.getConnection().prepareStatement(sql3);
            stmt3.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            PreparedStatement stmt4 = DbConnect.getConnection().prepareStatement(sql4);
            stmt4.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "You were deleted all bills successfully.");
        /* Login drugdeleted = new Login();
        drugdeleted.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_dltbilActionPerformed

    private void dltallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltallActionPerformed
        String sql = "DROP TABLE store";
        String sql2 = "CREATE TABLE `store` (\n" +
        "  `id` int(11) NOT NULL,\n" +
        "  `BatchNo` varchar(6) DEFAULT NULL,\n" +
        "  `GName` varchar(50) DEFAULT NULL,\n" +
        "  `BName` varchar(50) DEFAULT NULL,\n" +
        "  `Qty` int(4) DEFAULT NULL,\n" +
        "  `MRP` double DEFAULT NULL,\n" +
        "  `Exp` date DEFAULT NULL\n" +
        ") ENGINE=InnoDB DEFAULT CHARSET=latin1;";
        String sql3 = "ALTER TABLE `store`\n" +
        "  ADD PRIMARY KEY (`id`);";
        String sql4 = "ALTER TABLE `store`\n" +
        "  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;";
        try {
            PreparedStatement stmt = DbConnect.getConnection().prepareStatement(sql);
            stmt.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            PreparedStatement stmt2 = DbConnect.getConnection().prepareStatement(sql2);
            stmt2.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            PreparedStatement stmt3 = DbConnect.getConnection().prepareStatement(sql3);
            stmt3.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            PreparedStatement stmt4 = DbConnect.getConnection().prepareStatement(sql4);
            stmt4.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "You were deleted all drug items successfully.");
        /*  Login drugdeleted = new Login();
        drugdeleted.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_dltallActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Additems loginuser = new Additems();
        MainWindow mw = new MainWindow(loginuser);
        mw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void additembutnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additembutnActionPerformed
        Additems AI = new Additems();
        AI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_additembutnActionPerformed

    private void deleteitembutnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteitembutnActionPerformed
        Deleteitem DI = new Deleteitem();
        DI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteitembutnActionPerformed

    private void viewstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstockActionPerformed
        ViewStock VS = new ViewStock();
        VS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewstockActionPerformed

    private void viewbillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbillsActionPerformed
        ViewPreviousBills vb = new ViewPreviousBills();
        vb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewbillsActionPerformed

    private void viewstock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstock1ActionPerformed
        ViewStock VS = new ViewStock();
        VS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewstock1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deleteitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deleteitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deleteitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deleteitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Deleteitem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additembutn;
    private javax.swing.JButton back;
    private javax.swing.JTextField bno;
    private javax.swing.JButton deleteitembutn;
    private javax.swing.JButton dlt;
    private javax.swing.JButton dltall;
    private javax.swing.JButton dltbil;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewbills;
    private javax.swing.JButton viewstock;
    private javax.swing.JButton viewstock1;
    // End of variables declaration//GEN-END:variables
}
