/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoyalPharma;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author Thisarani
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form RoyalPharmacy
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbAccessLevel = new javax.swing.JComboBox<String>();
        uId = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        lblForgotPassword = new javax.swing.JLabel();
        logbtn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome !");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pharmacy Management System");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 510, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("PASSWORD:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 226, 120, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ACCESS LEVEL :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("USER ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 178, 120, 30));

        cmbAccessLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal User", "Admin" }));
        cmbAccessLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccessLevelActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAccessLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 200, -1));

        uId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uIdActionPerformed(evt);
            }
        });
        jPanel1.add(uId, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 184, 205, -1));

        pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 226, 205, -1));

        lblForgotPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(0, 0, 255));
        lblForgotPassword.setText("Forgot Password..?");
        lblForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(lblForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 140, 30));

        logbtn.setBackground(new java.awt.Color(255, 255, 255));
        logbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logbtn.setForeground(new java.awt.Color(102, 153, 255));
        logbtn.setText("Login");
        logbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 170, 40));

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(102, 153, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 170, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/loginuser.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/username.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/password.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/Royal_KM.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 210, 130));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoyalPharma/shutterstock_medicine_tablets (1).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uIdActionPerformed

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed

        LoginClass loginuser = new LoginClass();
        boolean isUser = false;

        loginuser.setUId(Integer.parseInt(uId.getText()));
        Integer id = loginuser.getUId();

        loginuser.setPass(String.valueOf(pass.getText()));
        String password = loginuser.getPass();

        loginuser.setULevel(cmbAccessLevel.getSelectedItem().toString());
        String userLevel = loginuser.getULevel();

        String sql = "SELECT * FROM user_details WHERE user_id=? and password=? and user_level=?";

        try {
            PreparedStatement stmt = DbConnect.getConnection().prepareStatement(sql);
            stmt.setInt(1, id);
            stmt.setString(2, password);
            stmt.setString(3, userLevel);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {

                isUser = true;
                LoginClass.uId = id;
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

        String sqlmaxid = "SELECT MAX(user_id)FROM user_details";
        try {
            PreparedStatement stmt = DbConnect.getConnection().prepareStatement(sqlmaxid);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
//                billnumlab.setText(String.valueOf(rs.getInt(1) + 1));
                NewUser.userID = rs.getInt(1) + 1;
                System.out.println(NewUser.userID + "MAX ID....................................");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();

        } catch (Exception e) {
            e.printStackTrace();

        }

        if ("".equals(uId) || "".equals(pass)) {
            JOptionPane.showMessageDialog(null, "Please input your username and password");
        } else if (!isUser) {
            JOptionPane.showMessageDialog(null, "Invalid username or password.");
        } else if (isUser) {
            if (loginuser.getULevel().equals("Normal User")) {
                MainWindow user = new MainWindow(loginuser);
                JOptionPane.showMessageDialog(null, "You are Welcome.");
                user.setVisible(true);
                this.dispose();
            } else if (loginuser.getULevel().equals("Admin")) {

            }
        }
    }//GEN-LAST:event_logbtnActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbAccessLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccessLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAccessLevelActionPerformed

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseClicked
        Changepassword CPLogin = new Changepassword();
        CPLogin.setVisible(true);
    }//GEN-LAST:event_lblForgotPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbAccessLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JButton logbtn;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField uId;
    // End of variables declaration//GEN-END:variables
}
